version: '3.7'
services:
  ldap_server:
    image: openldap
    environment:
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_BASE_DN: dc=zubcevic,dc=com
    ports:
      - 389:389
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldap_data:
  ldap_config:
